version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.7
    commands:
        - python --version
        #- python -m pip3 install Flask
        #- python3 -m pip install pip --upgrade
        #- sudo yum install python3-pip
        #- pip install --upgrade pip
        #- pip install --upgrade awscli
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -e .
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
